# Generated by Django 4.0.3 on 2022-05-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='signup_enabled',
            field=models.BooleanField(default=False, verbose_name='是否开放注册'),
        ),
    ]
